name: Go

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Install DB
      run: docker compose up -d

    - name: Wait for MySQL
      run: |
        for i in {1..10}; do
          if docker exec db mysqladmin ping -uroot -p${{ secrets.DB_PASSWORD }} --silent; then
            echo "MySQL is ready!"
            exit 0
          fi
          echo "Waiting for MySQL..."
          sleep 5
        done
        echo "MySQL is not ready in time."
        exit 1

    - name: Check mysql
      run: docker exec db mysql -uroot -p${{ secrets.DB_PASSWORD }} -e "USE advent_calendar; SELECT 'Database exists!' AS Result;"

    - name: Test
      run: make test
