# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Install DB
      run: docker compose up -d

    - name: Check mysql
      run: docker exec db mysql -uroot -p${{ secrets.DB_PASSWORD }} -e "USE advent_calendar; SELECT 'Database exists!' AS Result;" 

    - name: Test
      run: make test
    
